### ISSUE TITLE
0.94 version crashed on Linux

### ISSUE THREAD

**Issue by MikaelBox** [Ethck/Path-of-Accounting#178]
```
[*] Loaded 14656 bases and their prices.
Traceback (most recent call last):
  File "Accounting.py", line 194, in <module>
    watch_keyboard(keyboard, USE_HOTKEYS)
  File "Accounting.py", line 101, in watch_keyboard
    keyboard.add_hotkey(HIDEOUT, lambda: keyboard.write("\n/hideout\n"))
  File "/home/mikaelbox/useful_soft/poe_accounting/utils/input.py", line 41, in add_hotkey
    keyboard.add_hotkey(key, lambda: self.queue.put(key))
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/mikaelbox/.local/lib/python3.7/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```

Version 0.93 works fine

**Comment by rhzk** [comment]
You need to run it with sudo on linux

**Comment by Ethck** [comment]
We were having issues with the alternative library, so v0.94 has temporarily disabled that library. You will need to run as root because the keyboard library reads /proc files to determine which keys are pressed.

**Comment by MikaelBox** [comment]
Thx
