### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by InFerYes** [Ethck/Path-of-Accounting#181]
```python3 ./parse.py                                                                          :(
[*] Watching clipboard (Ctrl+C to stop)...
[*] Found Rare item in clipboard: Havoc Bond Stygian Vise
[+] Found mod +147 to Armour (Local)
[+] Found mod +147 to Armour
[+] Found mod +61 to maximum Life
[+] Found mod +40 to maximum Mana
[+] Found mod +12% to Cold Resistance
[+] Found mod +28% to Lightning Resistance (crafted)
[o] Combining the elemental resistance mods from the list into a pseudo-parameter
[+] Pseudo-mod +40% total Elemental Resistance (pseudo)
[o] Combining the maximum life mods from the list into a pseudo-parameter
[+] Pseudo-mod +61 to maximum Life (pseudo)
[-] Removing the # to Armour mod from the list due to no results found.
[-] Removing the # to maximum Mana mod from the list due to no results found.
[-] Removing the +# total maximum Life mod from the list due to no results found.
[!] Take any values after this with a grain of salt. You should probably do a MANUAL search
[-] Removing the +#% total Elemental Resistance mod from the list due to no results found.
Traceback (most recent call last):
  File "./parse.py", line 668, in <module>
    watch_clipboard()
  File "./parse.py", line 624, in watch_clipboard
    trade_info = query_trade(**{k:v for k, v in info.items() if k in ('name', 'itype', 'ilvl', 'links',
  File "./parse.py", line 278, in query_trade
    results = fetch(res)
  File "./parse.py", line 155, in fetch
    print(f'[!] Trade result retrieval failed: HTTP {res.status_code}! '
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Ethck** [comment]
What version of Path of Accounting are you using? Please make sure you are using the latest version. I can't seem to reproduce this error, and some of the content in this debug message shows that this is a very old version. Let me know if updating works for you.

**Comment by rhzk** [comment]
Look like a old version, hes starting it with python3 parse.py, not Accounting.py

**Comment by InFerYes** [comment]
I pulled the latest version and copied it over the old folder. I will try Accounting.py, thank you.

I need to fix some dependencies

edit1:
```
python3 ./Accounting.py                                                                     :(
Traceback (most recent call last):
  File "./Accounting.py", line 7, in <module>
    from gui.gui import check_timeout_gui, close_all_windows, init_gui
  File "/home/user/Games/path-of-accounting/gui/gui.py", line 6, in <module>
    import screeninfo
ModuleNotFoundError: No module named 'screeninfo'

```
```
pip3 install -r requirements.txt                                                            :(
zsh: correct 'pip3' to 'ypipe' [nyae]? n
zsh: command not found: pip3

```

edit2: uh oh

```
sudo pacman -S pip3                                                                         :(
[sudo] password for user: 
error: target not found: pip3

```

edit3:
```
pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Ignoring pypiwin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Collecting attr==0.3.1
  Downloading attr-0.3.1.tar.gz (1.7 kB)
Requirement already satisfied: attrs==19.3.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.4.3)
Collecting dataclasses==0.6
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting idna==2.8
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.7 MB/s 
Collecting keyboard==0.13.4
  Downloading keyboard-0.13.4-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.6 MB/s 
Collecting Pillow==7.0.0
  Downloading Pillow-7.0.0-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 17.4 MB/s 
Collecting pynput==1.6.6
  Downloading pynput-1.6.6-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 7.8 MB/s 
Collecting pyperclip==1.7.0
  Downloading pyperclip-1.7.0.tar.gz (15 kB)
Collecting requests==2.22.0
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 7.8 MB/s 
Collecting requests-mock==1.7.0
  Downloading requests_mock-1.7.0-py2.py3-none-any.whl (23 kB)
Collecting screeninfo==0.6.1
  Downloading screeninfo-0.6.1.tar.gz (5.8 kB)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.14.0)
Collecting tqdm==4.41.1
  Downloading tqdm-4.41.1-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 7.1 MB/s 
Collecting typing==3.7.4.1
  Downloading typing-3.7.4.1-py3-none-any.whl (25 kB)
Collecting urllib3==1.25.7
  Downloading urllib3-1.25.7-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 20.0 MB/s 
Collecting timeago==1.0.13
  Downloading timeago-1.0.13.tar.gz (24 kB)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /usr/lib/python3.8/site-packages (from pynput==1.6.6->-r requirements.txt (line 10)) (0.26)
Installing collected packages: attr, dataclasses, idna, keyboard, Pillow, pynput, pyperclip, urllib3, requests, requests-mock, screeninfo, tqdm, typing, timeago
    Running setup.py install for attr ... done
    Running setup.py install for pyperclip ... done
    Running setup.py install for screeninfo ... done
  WARNING: The script tqdm is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for timeago ... done
Successfully installed Pillow-7.0.0 attr-0.3.1 dataclasses-0.6 idna-2.8 keyboard-0.13.4 pynput-1.6.6 pyperclip-1.7.0 requests-2.22.0 requests-mock-1.7.0 screeninfo-0.6.1 timeago-1.0.13 tqdm-4.41.1 typing-3.7.4.1 urllib3-1.25.7

```

which finally leads me to

```
ython3 ./Accounting.py         
Traceback (most recent call last):
  File "./Accounting.py", line 8, in <module>
    from gui.windows import gearInformation, information
  File "/home/user/Games/path-of-accounting/gui/windows.py", line 9, in <module>
    from item.generator import Weapon
  File "/home/user/Games/path-of-accounting/item/generator.py", line 7, in <module>
    from item.itemModifier import ItemModifierType
  File "/home/user/Games/path-of-accounting/item/itemModifier.py", line 3, in <module>
    from attr import attrs
ImportError: cannot import name 'attrs' from 'attr' (/home/user/.local/lib/python3.8/site-packages/attr.py)

```

**Comment by rhzk** [comment]
Try running it with sudo, pip is weird on linux, it installs packages in multiple places and for some reason cant find them later

**Comment by Ethck** [comment]
Try installing the attrs library. I'll look over the requirements folder and provide some additional instructions in the README when I update it next.

**Comment by InFerYes** [comment]
> Try running it with sudo, pip is weird on linux, it installs packages in multiple places and for some reason cant find them later

Sorry, same issue:

```
1 user@ranger ~/Games/path-of-accounting % sudo pip3 install -r requirements.txt                                                       :(
[sudo] password for user: 
Ignoring pypiwin32: markers 'platform_system == "Windows"' don't match your environment
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Collecting attr==0.3.1
  Downloading attr-0.3.1.tar.gz (1.7 kB)
Requirement already satisfied: attrs==19.3.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: certifi==2019.11.28 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.4.3 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.4.3)
Collecting dataclasses==0.6
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting idna==2.8
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.8 MB/s 
Collecting keyboard==0.13.4
  Downloading keyboard-0.13.4-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 7.5 MB/s 
Collecting Pillow==7.0.0
  Downloading Pillow-7.0.0-cp38-cp38-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.7 MB/s 
Collecting pynput==1.6.6
  Downloading pynput-1.6.6-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 9.0 MB/s 
Collecting pyperclip==1.7.0
  Downloading pyperclip-1.7.0.tar.gz (15 kB)
Collecting requests==2.22.0
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 7.8 MB/s 
Collecting requests-mock==1.7.0
  Downloading requests_mock-1.7.0-py2.py3-none-any.whl (23 kB)
Collecting screeninfo==0.6.1
  Downloading screeninfo-0.6.1.tar.gz (5.8 kB)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.14.0)
Collecting tqdm==4.41.1
  Downloading tqdm-4.41.1-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 7.2 MB/s 
Collecting typing==3.7.4.1
  Downloading typing-3.7.4.1-py3-none-any.whl (25 kB)
Collecting urllib3==1.25.7
  Downloading urllib3-1.25.7-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 18.7 MB/s 
Collecting timeago==1.0.13
  Downloading timeago-1.0.13.tar.gz (24 kB)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /usr/lib/python3.8/site-packages (from pynput==1.6.6->-r requirements.txt (line 10)) (0.26)
Installing collected packages: attr, dataclasses, idna, keyboard, Pillow, pynput, pyperclip, urllib3, requests, requests-mock, screeninfo, tqdm, typing, timeago
    Running setup.py install for attr ... done
  Attempting uninstall: idna
    Found existing installation: idna 2.9
    Uninstalling idna-2.9:
      Successfully uninstalled idna-2.9
  Attempting uninstall: Pillow
    Found existing installation: Pillow 6.2.1
    Uninstalling Pillow-6.2.1:
      Successfully uninstalled Pillow-6.2.1
    Running setup.py install for pyperclip ... done
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.8
    Uninstalling urllib3-1.25.8:
      Successfully uninstalled urllib3-1.25.8
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
    Running setup.py install for screeninfo ... done
    Running setup.py install for timeago ... done
Successfully installed Pillow-7.0.0 attr-0.3.1 dataclasses-0.6 idna-2.8 keyboard-0.13.4 pynput-1.6.6 pyperclip-1.7.0 requests-2.22.0 requests-mock-1.7.0 screeninfo-0.6.1 timeago-1.0.13 tqdm-4.41.1 typing-3.7.4.1 urllib3-1.25.7
user@ranger ~/Games/path-of-accounting % python3 ./Accounting.py              
Traceback (most recent call last):
  File "./Accounting.py", line 8, in <module>
    from gui.windows import gearInformation, information
  File "/home/user/Games/path-of-accounting/gui/windows.py", line 9, in <module>
    from item.generator import Weapon
  File "/home/user/Games/path-of-accounting/item/generator.py", line 7, in <module>
    from item.itemModifier import ItemModifierType
  File "/home/user/Games/path-of-accounting/item/itemModifier.py", line 3, in <module>
    from attr import attrs
ImportError: cannot import name 'attrs' from 'attr' (/home/user/.local/lib/python3.8/site-packages/attr.py)

```

**Comment by InFerYes** [comment]
> Try installing the attrs library. I'll look over the requirements folder and provide some additional instructions in the README when I update it next.

It says the attrs package is "already satisfied"

```
Collecting attr==0.3.1
  Downloading attr-0.3.1.tar.gz (1.7 kB)
Requirement already satisfied: attrs==19.3.0 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (19.3.0)
```

```
usr@ranger ~ % ls /usr/lib/python3.8/site-packages | grep attr
attr
attr.py
attrs-19.3.0-py3.8.egg-info
attr-0.3.1-py3.8.egg-info
dry_attr.py
```

**Comment by InFerYes** [comment]
Final update: I have removed the user-specific lib folder `(/home/usr/.local/lib/python3.8/site-packages/)`

Then when I tried to run Accounting.py it said `raise ImportError('You must be root to use this library on linux.')`

```
1 user@ranger ~/Games/path-of-accounting % python ./Accounting.py                                                                      :(
If you wish to change the selected league you may do so in settings.cfg.
Valid league values are Delirium, Hardcore Delirium, Standard, Hardcore.
All values will be from the Delirium league
[*] Loaded 18017 bases and their prices.
Traceback (most recent call last):
  File "./Accounting.py", line 194, in <module>
    watch_keyboard(keyboard, USE_HOTKEYS)
  File "./Accounting.py", line 101, in watch_keyboard
    keyboard.add_hotkey(HIDEOUT, lambda: keyboard.write("\n/hideout\n"))
  File "/home/user/Games/path-of-accounting/utils/input.py", line 41, in add_hotkey
    keyboard.add_hotkey(key, lambda: self.queue.put(key))
  File "/usr/lib/python3.8/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/usr/lib/python3.8/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/usr/lib/python3.8/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/usr/lib/python3.8/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/usr/lib/python3.8/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/usr/lib/python3.8/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
```

So I ran Accounting.py with sudo and now it works.

So for me on Arch it was: install package `python-pip`, then run the pip3 command with `sudo` to install the requirements, then also run Accounting.py itself with `sudo`.

**Comment by rhzk** [comment]
Its a bit annoying, pip seems to install to 2 different places 
"/usr/lib/python3.8/site-packages" (when run with sudo, also seems to put some packages here by default) and 
"home/user/.local/lib/python3.8/site-packages/" (without sudo, or is it the other way around?)
But for some reason can't access one of them when running python..
We think it might be a permission problem or path problem
