### ISSUE TITLE
Error when parsing organs

### ISSUE THREAD

**Issue by Vilsol** [Ethck/Path-of-Accounting#191]
When trying to price-check the following organ:

```
Rarity: Unique
Beast of the Pits's Heart
--------
Uses: Rock Storm
--------
Item Level: 74
--------
Drops additional Rare Jewellery
Drops additional Rare Jewellery
Drops additional Currency Items
--------
Combine this with four other different samples in Tane's Laboratory.
```

I get this error:

```python
Traceback (most recent call last):
  File "utils\input.py", line 27, in poll
    self.hotkeys[key]()
  File "Accounting.py", line 105, in <lambda>
  File "Accounting.py", line 89, in hotkey_handler
  File "utils\parse.py", line 50, in basic_search
    item = parse_item_info(text)
  File "item\generator.py", line 1027, in parse_item_info
    return parse_organ(regions, name)
  File "item\generator.py", line 928, in parse_organ
    if mod not in mods:
  File "<attrs generated hash 520ba5236cb2a2d57d661d022db0a284bacf6d40>", line 7, in __hash__
    self.options,
TypeError: unhashable type: 'dict'
```

Using release: v0.94

**Comment by rhzk** [comment]
Thanks for the report, should be fixed in the next release
