### ISSUE TITLE
Crash on Identify

### ISSUE THREAD

**Issue by Fryyyyy** [Ethck/Path-of-Accounting#37]
```
[*] Found Rare item in clipboard: Honour Sever Lion Sword
[+] Found mod # to Accuracy Rating (implicit)
[+] Found mod # to Level of Socketed Melee Gems
[+] Found mod #% increased Attack Speed (Local)
[+] Found mod #% increased Attack Speed
[+] Found mod # to Accuracy Rating
[+] Found mod # to Accuracy Rating (Local)
[+] Found mod Attacks have #% chance to cause Bleeding
[+] Found mod #% increased Damage with Bleeding
[+] Found mod #% increased Attack Speed if you've Killed Recently
[-] Removing the #% increased Attack Speed if you've Killed Recently mod from the list due to no results found.
[-] Removing the #% increased Damage with Bleeding mod from the list due to no results found.
[-] Removing the Attacks have #% chance to cause Bleeding mod from the list due to no results found.
[-] Removing the # to Accuracy Rating (Local) mod from the list due to no results found.
[-] Removing the #% increased Attack Speed mod from the list due to no results found.
[!] Take any values after this with a grain of salt. You should probably do a MANUAL search
[-] Removing the # to Level of Socketed Melee Gems mod from the list due to no results found.
[!] Take any values after this with a grain of salt. You should probably do a MANUAL search
[-] Removing the # to Accuracy Rating mod from the list due to no results found.
Traceback (most recent call last):
  File "parse.py", line 488, in <module>
  File "parse.py", line 453, in watch_clipboard
  File "parse.py", line 453, in <listcomp>
TypeError: format requires a mapping
[6376] Failed to execute script parse
```

Item is:
```Rarity: Rare
Honour Sever
Lion Sword
--------
Two Handed Sword
Quality: +20% (augmented)
Physical Damage: 68-113 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.65 (augmented)
Weapon Range: 13
--------
Requirements:
Level: 65
Str: 104
Dex: 122
--------
Sockets: B-R-G 
--------
Item Level: 74
--------
+470 to Accuracy Rating (implicit)
--------
+1 to Level of Socketed Melee Gems
18% increased Attack Speed
+197 to Accuracy Rating
Attacks have 20% chance to cause Bleeding
28% increased Damage with Bleeding
20% increased Attack Speed if you've Killed Recently
--------
Elder Item
--------
```

**Comment by Ethck** [comment]
I have not been able to reproduce this error, but I have a good idea how to fix it.

**Comment by Ethck** [comment]
As far as I can tell, the error is fixed in the latest `dev` branch.
